blank_issues_enabled: true
contact_links:
  - name: ðŸ“– Documentation
    url: https://github.com/Polar-Team/diffusion/blob/main/README.md
    about: Read the documentation to learn more about Diffusion
  - name: ðŸ’¬ GitHub Discussions
    url: https://github.com/Polar-Team/diffusion/discussions
    about: Join the community discussion for general questions and conversations
